[project]
name = "sammy-cayo-take-home"
version = "0.1.0"
description = "full stack application for log analysis and threat detection"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "httpx>=0.28",
    "passlib>=1.7.4",
    "psycopg[binary]>=3.3.5",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.32",
    "sqlalchemy>=2.0.54",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.7",
]
